# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bg_ML <- function(y0, y1, t, n_samples, alpha_mean, alpha_sd, alpha_prop_sd) {
    .Call('_SimReg_bg_ML', PACKAGE = 'SimReg', y0, y1, t, n_samples, alpha_mean, alpha_sd, alpha_prop_sd)
}

f_ML <- function(x_values, num_y0_phi, num_y1_phi, t, log_scale_tolerance, min_samples, max_samples, min_log_ML, alpha_mean, alpha_sd, log_beta_mean, log_beta_sd, logit_f_mean, logit_f_sd, log_f_a_plus_b_mean, log_f_a_plus_b_sd, alpha_prop_sd, log_beta_prop_sd, logit_f_mean_prop_sd, log_f_a_plus_b_prop_sd) {
    .Call('_SimReg_f_ML', PACKAGE = 'SimReg', x_values, num_y0_phi, num_y1_phi, t, log_scale_tolerance, min_samples, max_samples, min_log_ML, alpha_mean, alpha_sd, log_beta_mean, log_beta_sd, logit_f_mean, logit_f_sd, log_f_a_plus_b_mean, log_f_a_plus_b_sd, alpha_prop_sd, log_beta_prop_sd, logit_f_mean_prop_sd, log_f_a_plus_b_prop_sd)
}

ML <- function(s_phi_values, s_x_values, num_y0_phi, num_y1_phi, t, log_scale_tolerance, min_samples, max_samples, min_log_ML, alpha_mean, alpha_sd, log_beta_mean, log_beta_sd, logit_f_mean, logit_f_sd, log_f_a_plus_b_mean, log_f_a_plus_b_sd, logit_g_mean, logit_g_sd, log_g_a_plus_b_mean, log_g_a_plus_b_sd, alpha_prop_sd, log_beta_prop_sd, logit_f_mean_prop_sd, log_f_a_plus_b_prop_sd, logit_g_mean_prop_sd, log_g_a_plus_b_prop_sd) {
    .Call('_SimReg_ML', PACKAGE = 'SimReg', s_phi_values, s_x_values, num_y0_phi, num_y1_phi, t, log_scale_tolerance, min_samples, max_samples, min_log_ML, alpha_mean, alpha_sd, log_beta_mean, log_beta_sd, logit_f_mean, logit_f_sd, log_f_a_plus_b_mean, log_f_a_plus_b_sd, logit_g_mean, logit_g_sd, log_g_a_plus_b_mean, log_g_a_plus_b_sd, alpha_prop_sd, log_beta_prop_sd, logit_f_mean_prop_sd, log_f_a_plus_b_prop_sd, logit_g_mean_prop_sd, log_g_a_plus_b_prop_sd)
}

transform <- function(q, shape1, shape2, windows = 5L) {
    .Call('_SimReg_transform', PACKAGE = 'SimReg', q, shape1, shape2, windows)
}

sumgrid <- function(s_phi, s_x, breaks) {
    .Call('_SimReg_sumgrid', PACKAGE = 'SimReg', s_phi, s_x, breaks)
}

